[database]
node_uri= "mongodb://127.0.0.1:27017/?connect=direct&authSource=irita"
database= "irita"

[server]
ip_port="127.0.0.1:8787"
node_urls="http://127.0.0.1:26657"
worker_num_create_task=1
worker_num_execute_task=30
worker_max_sleep_time=120
block_num_per_worker_handle=100
max_connection_num=100
init_connection_num=5
bech32_acc_prefix="iaa"
chain_id="testnet"
chain_block_interval=5
behind_block_num=0
promethous_port=26660
support_modules=""
deny_modules=""
support_types=""
ignore_ibc_header=false
start_task=true